### ISSUE TITLE
Consider removing direct dependency on npx

### ISSUE THREAD

**Issue by ballPointPenguin** [kellyselden/boilerplate-update#316]
The distributed npx library is deprecated and now is handled within the npm distribution.
https://github.com/npm/npx#readme

This means that the npx library being required here will be stuck at v10.2, which in turn requires npm 5.x, which (I think) is sometimes causing problems with ember-cli-update because it uses an older version of graceful-fs.

I realize this is a long cause-and-effect chain of my insinuation. I am experiencing `cb.apply is not a function` when trying to run ember-cli-update, and so far this is the best guess that I have.

**Comment by ballPointPenguin** [comment]
Related to https://github.com/ember-cli/ember-cli-update/issues/1105

**Comment by kellyselden** [comment]
I think enough time has progressed, and we can assume npx is already on the machine. I think we can remove it.

**Comment by aberres** [comment]
@kellyselden Out of curiosity, I ended up here when looking into why we install an old deprecated `tar`.  Any plans to drop the dependency?

**Comment by kellyselden** [comment]
I'm open to the change, but I'm not planning on doing the work myself.
